### ISSUE TITLE
Symbol usage forces exposure of "implementation details"

### ISSUE THREAD

**Issue by domenic** [michaelficarra/proposal-first-class-protocols#15]
Right now the proposal relies on symbols to express the requirements on the implementing classes. However, this unfortunately forces the implementing classes to expose their implementation details, which are now publicly accessible via `classInstance[Protocol.symbol]`.

For example, consider if we wanted to use this feature to implement something like DOM's [NonDocumentTypeChildNode](https://dom.spec.whatwg.org/#nondocumenttypechildnode), which is implemented by the Element and CharacterData classes. Assuming #14 is solved, to implement this seems like it would require exposing the Node's internal pointers backward and forward as symbols.

I'd be interested in a few variants:

- Allowing a different expression of the requirements on implementers. For example, requiring that they have `previousSibling` and `nexSibling` public properties, not symbol-named, but just normal ones. This would not be usable for DOM, which cannot allow monkeypatching of those properties to impact the processing model for `previousElementSibling` / `nextElementSibling`. But would be more usable for libraries, I think.
- Some kind of shared private symbol, tied to the recent work on the private state proposal. I have no idea how this would work; maybe syntactically extending it brings it into lexical scope or something.

The symbol usage doesn't seem to work very well though. I think this is especially apparent given how it requires creating holder objects (like the README's `ToString`) instead of being able to leverage existing protocols (like `Symbol.toStringTag`).

**Comment by Jamesernator** [comment]
I wonder if there could be some form of dynamic private name definition to allow external PrivateNames being used as part of another class:

```js
protocol Monad {
    #map(iteratee)
}

function map(iteratee) {
    // Obviously the private name would need to be dynamically accessible
    // outside the class too otherwise it's a bit pointless
    return value => value.#[Monad.map]()

class Box implements Monad {
    #value
    constructor(value) {
        this.#value = value
    }
    // Where Monad.map is a PrivateName
    #[Monad.map](iteratee) {
        return new Box(iteratee(this.#value))
    }
}

const twenty = map(x => x*2)(new Box(10))
```

---

Regarding public names I wonder if there could be a thing for protocols to throw an error if multiple protocols are attempted to be applied that have the same name so that protocols can't break each other (although you'd still want a way to implement multiple conflicting protocols if there's a way to satisfy both).

**Comment by michaelficarra** [comment]
@domenic I don't really understand your point about "implementation details" or private symbols. Protocols are inherently about specifying a minimum public API. I don't think your use case fits well with that.

On your point of leveraging existing protocols, see the dynamic protocol API (currently documented in [slides](https://docs.google.com/presentation/d/1WrvSyslnF-5VnPj3k3HRq8MRzuiSN1kQ6ENE1iUSmDU/edit?usp=sharing) 16 through 18). I will add more about that to the README soon.

**Comment by domenic** [comment]
Yes, it does seem possible this proposal is for an even more narrow use case than I anticipated.

**Comment by michaelficarra** [comment]
Okay, I'm going to close this then.
