### ISSUE TITLE
Multi implements keyword is confused.

### ISSUE THREAD

**Issue by brn** [michaelficarra/proposal-first-class-protocols#21]
Usage of `implements` keyword below

```
class C implements I implements K {}
```

is very confused and verbose, because TypeScript implements interface extension as like below.

```
class Class implements InterfaceA, InterfaceB {}
```

So I think above usage of `implements` keyword is more compatible and familiar.

**Comment by michaelficarra** [comment]
@brn That's actually just a bug in the README. The implementation already supports the syntax you suggest.
