### ISSUE TITLE
Iterable protocol

### ISSUE THREAD

**Issue by thejameskyle** [michaelficarra/proposal-first-class-protocols#22]
Note: I'm not suggesting that be added to this proposal, just that it be briefly considered.

---

There's an argument to be made that there should be an `Iterable` protocol to "explain" the `Symbol.iterator` API.

```js
protocol Iterable {
  iterator;
}

class Collection implements Iterable {
  [Iterable.iterator]() {
    // ...
  }
}
```

The only problem with this would be the reference equality of `Symbol.iterator` and `Iterable` for which there are two options:

```js
Symbol.iterator = Iterable.iterator
```

```js
protocol Iterable {
  iterator = Symbol.iterator; // some form of definition syntax: =, :, :=, ...
}
```

The former seems a lot easier, assuming the final proposal will have no observable difference.

It does sort of seem like this protocols design (in its current form) enables future API designs more than it explains existing ones like Thenables or Iterables.

**Comment by keithamus** [comment]
Another alternative is to just shim the protocol without using the keyword sugar:

```js
Iterable = Object.create(null, { 
  iterator: { value: Symbol.iterator },
})
```

**Comment by thejameskyle** [comment]
Ah, it seems this was brought up in the September meeting.

It seems like having a way to define the value of a protocol property would be necessary if this proposal were to explain thenables (with string properties):

```js
protocol Thenable {
  then = 'then';
}
```

**Comment by keithamus** [comment]
WRT strings, see #19. I believe the two are orthogonal. Iterator is an example of an existing Symbol based protocol. Thenables are an example of string based protocol.

**Comment by thejameskyle** [comment]
Another question would be if there should be a way to dynamically check if a value implements a protocol and then call the protocol methods on it, at least as a spec mechanism:

1. Let `value` be ...
1. If [`CheckImplements`](#) ( `value`, [`ThenableProtocol`](#) )  is `true`.
    1. [`Call`](#) ( [`ThenableProtocol.additionalMethod`](#) , `value` , `...args` ).

**Comment by michaelficarra** [comment]
@thejameskyle This was actually an example from [the slides I presented to TC39](https://docs.google.com/presentation/d/1WrvSyslnF-5VnPj3k3HRq8MRzuiSN1kQ6ENE1iUSmDU/edit?usp=sharing):

![slide](https://user-images.githubusercontent.com/218840/31087589-704fe8ce-a752-11e7-9790-9b11d15f83d0.png)

It will continue to be a goal to be able to represent this protocol, both from a spec standpoint and as a user of this feature. But as you say, adding the first-class representation of the iteration protocol should not be part of this proposal.
