### ISSUE TITLE
Why not using the interface keyword

### ISSUE THREAD

**Issue by iddan** [michaelficarra/proposal-first-class-protocols#28]
- It's used by Java & C#
 - It's used by Typescript Flowtype

**Comment by ljharb** [comment]
I believe Typescript's use of it is the primary reason this proposal isn't using it; see #3.

**Comment by michaelficarra** [comment]
> It's used by Typescript Flowtype

And it's exactly your association with that that makes the name infeasible. It's not the same feature. Closing as duplicate of #3.
