### ISSUE TITLE
Use of Reflect is inappropriate

### ISSUE THREAD

**Issue by domenic** [michaelficarra/proposal-first-class-protocols#9]
Right now Reflect only contains functions directly corresponding to MOP operations (as reified by proxy traps).

We should not extend Reflect with APIs for other purposes, even though its name is an attractive nuisance in that regard.

**Comment by michaelficarra** [comment]
I agree. I'm not aware of any already extant place which would be appropriate. Any suggestions?

**Comment by domenic** [comment]
Object seems pretty OK?

**Comment by ljharb** [comment]
`System`?

_/me runs away_ ᕕ( ᐛ )ᕗ

**Comment by gabejohnson** [comment]
Wouldn't #8 imply `Function`?

**Comment by ljharb** [comment]
That's a good point; if its first argument is only ever a constructor, `Function` might be the best place.

**Comment by michaelficarra** [comment]
This proposal now includes the `Protocol` constructor, and `Reflect.implement` has been moved to `Protocol.implement`.
